"""Add threats table

Revision ID: 69409dd2bd7b
Revises: 
Create Date: 2024-12-10 11:04:44.823150

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '69409dd2bd7b'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('threats',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=False),
    sa.Column('process_name', sa.String(), nullable=True),
    sa.Column('remote_ip', sa.String(), nullable=True),
    sa.Column('remote_port', sa.Integer(), nullable=True),
    sa.Column('connection_status', sa.String(), nullable=True),
    sa.Column('threat_type', sa.String(), nullable=True),
    sa.Column('resolved', sa.Integer(), nullable=True),
    sa.Column('resolution_time', sa.DateTime(), nullable=True),
    sa.Column('resolution_action', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('threats')
    # ### end Alembic commands ###
