"""add_performance_indexes

Revision ID: b24efbc07188
Revises: 69409dd2bd7b
Create Date: 2024-12-16 12:46:32.187678

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b24efbc07188'
down_revision: Union[str, None] = '69409dd2bd7b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('idx_alerts_type_severity', 'alerts', ['alert_type', 'severity'], unique=False)
    op.create_index(op.f('ix_alerts_alert_type'), 'alerts', ['alert_type'], unique=False)
    op.create_index(op.f('ix_alerts_resolved'), 'alerts', ['resolved'], unique=False)
    op.create_index(op.f('ix_alerts_severity'), 'alerts', ['severity'], unique=False)
    op.create_index(op.f('ix_alerts_timestamp'), 'alerts', ['timestamp'], unique=False)
    op.create_index('idx_network_conn_ips', 'network_connections', ['source_ip', 'destination_ip'], unique=False)
    op.create_index('idx_network_conn_timestamp', 'network_connections', ['timestamp'], unique=False)
    op.create_index(op.f('ix_network_connections_destination_ip'), 'network_connections', ['destination_ip'], unique=False)
    op.create_index(op.f('ix_network_connections_source_ip'), 'network_connections', ['source_ip'], unique=False)
    op.create_index(op.f('ix_network_connections_timestamp'), 'network_connections', ['timestamp'], unique=False)
    op.create_index('idx_system_metrics_timestamp', 'system_metrics', ['timestamp'], unique=False)
    op.create_index(op.f('ix_system_metrics_timestamp'), 'system_metrics', ['timestamp'], unique=False)
    op.create_index('idx_threats_ip_type', 'threats', ['remote_ip', 'threat_type'], unique=False)
    op.create_index(op.f('ix_threats_process_name'), 'threats', ['process_name'], unique=False)
    op.create_index(op.f('ix_threats_remote_ip'), 'threats', ['remote_ip'], unique=False)
    op.create_index(op.f('ix_threats_resolved'), 'threats', ['resolved'], unique=False)
    op.create_index(op.f('ix_threats_threat_type'), 'threats', ['threat_type'], unique=False)
    op.create_index(op.f('ix_threats_timestamp'), 'threats', ['timestamp'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_threats_timestamp'), table_name='threats')
    op.drop_index(op.f('ix_threats_threat_type'), table_name='threats')
    op.drop_index(op.f('ix_threats_resolved'), table_name='threats')
    op.drop_index(op.f('ix_threats_remote_ip'), table_name='threats')
    op.drop_index(op.f('ix_threats_process_name'), table_name='threats')
    op.drop_index('idx_threats_ip_type', table_name='threats')
    op.drop_index(op.f('ix_system_metrics_timestamp'), table_name='system_metrics')
    op.drop_index('idx_system_metrics_timestamp', table_name='system_metrics')
    op.drop_index(op.f('ix_network_connections_timestamp'), table_name='network_connections')
    op.drop_index(op.f('ix_network_connections_source_ip'), table_name='network_connections')
    op.drop_index(op.f('ix_network_connections_destination_ip'), table_name='network_connections')
    op.drop_index('idx_network_conn_timestamp', table_name='network_connections')
    op.drop_index('idx_network_conn_ips', table_name='network_connections')
    op.drop_index(op.f('ix_alerts_timestamp'), table_name='alerts')
    op.drop_index(op.f('ix_alerts_severity'), table_name='alerts')
    op.drop_index(op.f('ix_alerts_resolved'), table_name='alerts')
    op.drop_index(op.f('ix_alerts_alert_type'), table_name='alerts')
    op.drop_index('idx_alerts_type_severity', table_name='alerts')
    # ### end Alembic commands ###
